name: Image

on:
  create:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cakephp-fpm-alpine:latest --tag cakephp-fpm-alpine:$(echo ${GITHUB_REF#refs/*/})
